# Generated by Django 5.2.17 on 2026-08-22 03:18

import apps.core.ids
import apps.events.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('kind', models.CharField(choices=[('grading', 'Grading'), ('competition', 'Competition'), ('seminar', 'Seminar or course'), ('social', 'Social'), ('other', 'Other')], default='grading', max_length=20, verbose_name='kind')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='summary')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='place')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('price_minor_units', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('price_currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_note', models.CharField(blank=True, max_length=200, verbose_name='how to pay')),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='0 means no limit.', verbose_name='places')),
                ('rsvp_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='replies close')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('visibility', models.CharField(choices=[('private', 'Anyone with the link'), ('public', 'Public — anyone can find it')], default='private', max_length=10, verbose_name='who can see it')),
                ('public_token', models.CharField(default=apps.events.models.new_public_token, editable=False, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='identity.dojo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='identity.organization')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('party_size', models.PositiveSmallIntegerField(default=1, verbose_name='how many people')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='anything we should know')),
                ('status', models.CharField(choices=[('coming', 'Coming'), ('cancelled', 'Cancelled')], default='coming', max_length=12, verbose_name='status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'starts_at'], name='events_even_organiz_435a1a_idx'),
        ),
    ]
