# Generated by Django 5.2.17 on 2026-08-22 03:38

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('identity', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='answers'),
        ),
        migrations.CreateModel(
            name='EventFormField',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120, verbose_name='question')),
                ('kind', models.CharField(choices=[('text', 'Short answer'), ('paragraph', 'Long answer'), ('number', 'Number'), ('choice', 'Pick one'), ('checkbox', 'Tick box')], default='text', max_length=20, verbose_name='answer type')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='hint')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('options', models.TextField(blank=True, verbose_name='options')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='events.event')),
            ],
            options={
                'verbose_name': 'event form question',
                'verbose_name_plural': 'event form questions',
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
