# Generated by Django 5.2.17 on 2026-08-22 04:25

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_kind'),
        ('events', '0002_eventrsvp_answers_eventformfield'),
        ('identity', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image_for', to='core.document'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_qr_for', to='core.document'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='payment link'),
        ),
        migrations.AddField(
            model_name='event',
            name='plus_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='plus code'),
        ),
        migrations.AlterField(
            model_name='eventformfield',
            name='kind',
            field=models.CharField(choices=[('text', 'Short answer'), ('paragraph', 'Long answer'), ('number', 'Number'), ('choice', 'Pick one'), ('checkbox', 'Tick box'), ('file', 'File upload — proof of payment, say')], default='text', max_length=20, verbose_name='answer type'),
        ),
        migrations.CreateModel(
            name='RsvpAttachment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_id', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='question')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.eventrsvp')),
            ],
            options={
                'verbose_name': 'RSVP attachment',
                'verbose_name_plural': 'RSVP attachments',
                'ordering': ('created_at',),
            },
        ),
    ]
