# Independent expectations from plan sections 3 and 13.1 and SEC 2.2 and 4.
# Every allow-set is literal, so implementation changes cannot alter expectations.
from apps.identity.models import GovernanceModel, Role, ScopeType
from apps.identity.permissions import Action

CENTRAL = GovernanceModel.CENTRAL
FEDERATED = GovernanceModel.FEDERATED
ORG = ScopeType.ORG
DOJO = ScopeType.DOJO

MATRIX: dict[tuple[str, str, str], set[str]] = {
    (Role.ORG_ADMIN, ORG, CENTRAL): {
        Action.ORG_EDIT,
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.DOJO_CREATE,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.RANK_RATIFY,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.ORG_ADMIN, ORG, FEDERATED): {
        Action.ORG_EDIT,
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.DOJO_CREATE,
        Action.PERSON_VIEW,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.RANK_RATIFY,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.ORG_ADMIN, DOJO, CENTRAL): {
        Action.ORG_EDIT,
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.DOJO_CREATE,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.RANK_RATIFY,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.ORG_ADMIN, DOJO, FEDERATED): {
        Action.ORG_EDIT,
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.DOJO_CREATE,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.RANK_RATIFY,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.DOJO_ADMIN, ORG, CENTRAL): {
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.DOJO_ADMIN, ORG, FEDERATED): {
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.PERSON_VIEW,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.DOJO_ADMIN, DOJO, CENTRAL): {
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.DOJO_ADMIN, DOJO, FEDERATED): {
        Action.DOJO_VIEW,
        Action.DOJO_EDIT,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.PERSON_EXPORT,
        Action.MEDICAL_VIEW,
        Action.MEDICAL_EDIT,
        Action.ROLE_ASSIGN,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        Action.RANK_VIEW,
        Action.RANK_AWARD,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.TIMEENTRY_APPROVE,
        Action.REPORT_VIEW,
        Action.REPORT_VIEW_FINANCIAL,
    },
    (Role.INSTRUCTOR, ORG, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.INSTRUCTOR, ORG, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.INSTRUCTOR, DOJO, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.INSTRUCTOR, DOJO, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_WRITE,
        Action.TIMEENTRY_VIEW_OWN,
        Action.REPORT_VIEW,
    },
    (Role.ASSISTANT_INSTRUCTOR, ORG, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.TIMEENTRY_VIEW_OWN,
    },
    (Role.ASSISTANT_INSTRUCTOR, ORG, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.TIMEENTRY_VIEW_OWN,
    },
    (Role.ASSISTANT_INSTRUCTOR, DOJO, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.TIMEENTRY_VIEW_OWN,
    },
    (Role.ASSISTANT_INSTRUCTOR, DOJO, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.TIMEENTRY_VIEW_OWN,
    },
    (Role.FRONT_DESK, ORG, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.REPORT_VIEW,
    },
    (Role.FRONT_DESK, ORG, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.REPORT_VIEW,
    },
    (Role.FRONT_DESK, DOJO, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.REPORT_VIEW,
    },
    (Role.FRONT_DESK, DOJO, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.PERSON_EDIT,
        Action.PERSON_CREATE,
        Action.ATTENDANCE_VIEW,
        Action.ATTENDANCE_RECORD,
        Action.RANK_VIEW,
        Action.FINANCIAL_VIEW,
        Action.FINANCIAL_MANAGE,
        Action.REPORT_VIEW,
    },
    (Role.SAFEGUARDING, ORG, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.SAFEGUARDING_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
    },
    (Role.SAFEGUARDING, ORG, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.NOTE_WRITE,
    },
    (Role.SAFEGUARDING, DOJO, CENTRAL): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.SAFEGUARDING_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
    },
    (Role.SAFEGUARDING, DOJO, FEDERATED): {
        Action.DOJO_VIEW,
        Action.PERSON_VIEW,
        Action.MEDICAL_VIEW,
        Action.SAFEGUARDING_VIEW,
        Action.NOTE_VIEW_INSTRUCTOR,
        Action.NOTE_VIEW_ADMIN,
        Action.NOTE_WRITE,
    },
    (Role.GUARDIAN, ORG, CENTRAL): set(),
    (Role.GUARDIAN, ORG, FEDERATED): set(),
    (Role.GUARDIAN, DOJO, CENTRAL): set(),
    (Role.GUARDIAN, DOJO, FEDERATED): set(),
    (Role.STUDENT, ORG, CENTRAL): set(),
    (Role.STUDENT, ORG, FEDERATED): set(),
    (Role.STUDENT, DOJO, CENTRAL): set(),
    (Role.STUDENT, DOJO, FEDERATED): set(),
}

PINNED_CASES = [
    # role, scope, governance, action, expected
    (Role.ORG_ADMIN, ORG, CENTRAL, Action.FINANCIAL_VIEW, True),
    (Role.ORG_ADMIN, ORG, CENTRAL, Action.SAFEGUARDING_VIEW, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.FINANCIAL_VIEW, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.FINANCIAL_MANAGE, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.PERSON_EXPORT, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.MEDICAL_VIEW, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.SAFEGUARDING_VIEW, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.NOTE_VIEW_ADMIN, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.ROLE_ASSIGN, False),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.RANK_RATIFY, True),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.RANK_VIEW, True),
    (Role.ORG_ADMIN, ORG, FEDERATED, Action.DOJO_VIEW, True),
    # Instructors never see money.
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.FINANCIAL_VIEW, False),
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.FINANCIAL_MANAGE, False),
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.REPORT_VIEW_FINANCIAL, False),
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.MEDICAL_VIEW, True),
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.MEDICAL_EDIT, False),
    # Assistants cannot write notes, edit people, or alter past attendance.
    (Role.ASSISTANT_INSTRUCTOR, DOJO, CENTRAL, Action.NOTE_WRITE, False),
    (Role.ASSISTANT_INSTRUCTOR, DOJO, CENTRAL, Action.PERSON_EDIT, False),
    (
        Role.ASSISTANT_INSTRUCTOR,
        DOJO,
        CENTRAL,
        Action.ATTENDANCE_EDIT_RETROACTIVE,
        False,
    ),
    # Front desk handles money but must not change ranks or see medical data.
    (Role.FRONT_DESK, DOJO, CENTRAL, Action.FINANCIAL_MANAGE, True),
    (Role.FRONT_DESK, DOJO, CENTRAL, Action.RANK_AWARD, False),
    (Role.FRONT_DESK, DOJO, CENTRAL, Action.MEDICAL_VIEW, False),
    # Safeguarding notes are restricted to the named safeguarding role.
    (Role.SAFEGUARDING, DOJO, CENTRAL, Action.SAFEGUARDING_VIEW, True),
    (Role.DOJO_ADMIN, DOJO, CENTRAL, Action.SAFEGUARDING_VIEW, False),
    (Role.INSTRUCTOR, DOJO, CENTRAL, Action.SAFEGUARDING_VIEW, False),
    (Role.FRONT_DESK, DOJO, CENTRAL, Action.SAFEGUARDING_VIEW, False),
    # Guardians and students use separate portal-level object checks.
    (Role.GUARDIAN, DOJO, CENTRAL, Action.PERSON_VIEW, False),
    (Role.STUDENT, DOJO, CENTRAL, Action.PERSON_VIEW, False),
]
