# Generated by Django 5.2.16 on 2026-07-26 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('per_class', 'Per class'), ('salary', 'Salary'), ('volunteer', 'Volunteer')], max_length=16, verbose_name='pay type')),
                ('pay_rate_minor_units', models.PositiveIntegerField(default=0, verbose_name='pay rate (minor units)')),
                ('pay_currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('employment_started_on', models.DateField(blank=True, null=True, verbose_name='employment started on')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('max_grading_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_ceiling_for', to='ranks.rank')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to='identity.person')),
            ],
            options={
                'verbose_name': 'instructor profile',
                'verbose_name_plural': 'instructor profiles',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(blank=True, null=True, verbose_name='session id')),
                ('category', models.CharField(choices=[('class', 'Class'), ('admin', 'Admin'), ('private_lesson', 'Private lesson'), ('event', 'Event'), ('travel', 'Travel')], max_length=16, verbose_name='category')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16, verbose_name='status')),
                ('pay_rate_snapshot_minor_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='pay rate snapshot (minor units)')),
                ('pay_rate_snapshot_currency', models.CharField(blank=True, max_length=3, verbose_name='pay rate snapshot currency')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to='identity.person')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='identity.dojo')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='identity.person')),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ('-started_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='timeentry_ended_after_started')],
            },
        ),
    ]
