# Generated by Django 5.2.17 on 2026-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0004_style_is_ranked_alter_studentstyletrack_ladder'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='ranks.style', verbose_name='styles taught'),
        ),
    ]
