# Generated by Django 5.2.17 on 2026-08-19 04:13

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_user_must_change_password'),
        ('ranks', '0006_alter_rankladder_applies_to'),
        ('staffing', '0002_instructorprofile_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGrade',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='grade')),
                ('awarded_on', models.DateField(blank=True, null=True, verbose_name='awarded on')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_grades', to='identity.person')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_by_staff', to='ranks.rank')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_grades', to='ranks.style')),
            ],
            options={
                'verbose_name': 'staff grade',
                'verbose_name_plural': 'staff grades',
                'ordering': ('style__name',),
                'constraints': [models.UniqueConstraint(fields=('person', 'style'), name='staffgrade_one_per_person_per_style'), models.CheckConstraint(condition=models.Q(models.Q(('label', ''), ('rank__isnull', False)), models.Q(('rank__isnull', True), models.Q(('label', ''), _negated=True)), _connector='OR'), name='staffgrade_rank_or_label_not_both')],
            },
        ),
    ]
