# Generated by Django 5.2.16 on 2026-07-26 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('governance_model', models.CharField(choices=[('central', 'Centrally managed branches'), ('federated', 'Federation of independent dojos')], default='central', help_text="Determines whether the organisation can see member dojos' finances and full student records. Changing this after setup moves data ownership and must be done as a deliberate migration.", max_length=16, verbose_name='governance model')),
                ('country', models.CharField(default='KH', max_length=2, verbose_name='country')),
                ('default_timezone', models.CharField(default='Asia/Phnom_Penh', max_length=64, verbose_name='timezone')),
                ('default_currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_name', models.CharField(max_length=100, verbose_name='given name')),
                ('family_name', models.CharField(blank=True, max_length=100, verbose_name='family name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, verbose_name='preferred name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('locale', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('notes_summary', models.CharField(blank=True, editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='identity.organization')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ('family_name', 'given_name'),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person'),
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('timezone', models.CharField(default='Asia/Phnom_Penh', max_length=64, verbose_name='timezone')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('opened_on', models.DateField(blank=True, null=True, verbose_name='opened on')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='closed on')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dojos', to='identity.organization')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
            ],
            options={
                'verbose_name': 'dojo',
                'verbose_name_plural': 'dojos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_password_change', models.DateTimeField(blank=True, editable=False, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='identity.person')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('org_admin', 'Organisation administrator'), ('dojo_admin', 'Dojo administrator / head instructor'), ('instructor', 'Instructor'), ('assistant_instructor', 'Assistant instructor'), ('front_desk', 'Front desk'), ('safeguarding', 'Safeguarding officer'), ('guardian', 'Parent / guardian'), ('student', 'Adult student')], max_length=32, verbose_name='role')),
                ('scope_type', models.CharField(choices=[('org', 'Organisation'), ('dojo', 'Dojo')], max_length=8)),
                ('can_view_financials', models.BooleanField(default=False, verbose_name='may view financial data')),
                ('can_export_pii', models.BooleanField(default=False, verbose_name='may export personal data')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.dojo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.person')),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'family_name', 'given_name'], name='identity_pe_organiz_1ab8be_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'email'], name='identity_pe_organiz_338890_idx'),
        ),
        migrations.AddConstraint(
            model_name='dojo',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_dojo_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('person', 'role', 'scope_type', 'dojo'), name='unique_active_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dojo__isnull', False), ('scope_type', 'dojo')), models.Q(('dojo__isnull', True), ('scope_type', 'org')), _connector='OR'), name='role_scope_matches_dojo'),
        ),
    ]
