# Generated by Django 5.2.16 on 2026-07-26 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_person_deleted_at_person_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_head_instructor', models.BooleanField(default=False, verbose_name='head instructor')),
                ('started_on', models.DateField(verbose_name='started on')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='ended on')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='identity.dojo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='identity.person')),
            ],
            options={
                'verbose_name': 'instructor assignment',
                'verbose_name_plural': 'instructor assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('person', 'dojo'), name='unique_active_instructor_assignment')],
            },
        ),
    ]
