# Generated by Django 5.2.16 on 2026-07-26 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_instructorassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='relationship')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 = try first', verbose_name='priority')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='identity.person')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contacts',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('trial', 'Trial'), ('active', 'Active'), ('on_hold', 'On hold'), ('lapsed', 'Lapsed'), ('alumni', 'Alumni')], db_index=True, default='prospect', max_length=16, verbose_name='status')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='joined on')),
                ('hold_reason', models.CharField(blank=True, max_length=200, verbose_name='hold reason')),
                ('shirt_size', models.CharField(blank=True, max_length=20, verbose_name='shirt size')),
                ('gi_size', models.CharField(blank=True, max_length=20, verbose_name='gi size')),
                ('federation_licence_no', models.CharField(blank=True, max_length=100, verbose_name='federation licence number')),
                ('licence_expires_on', models.DateField(blank=True, null=True, verbose_name='licence expires on')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('home_dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_students', to='identity.dojo')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='identity.person')),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=16, verbose_name='relationship')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='primary contact')),
                ('is_emergency_contact', models.BooleanField(default=False, verbose_name='emergency contact')),
                ('is_financially_responsible', models.BooleanField(default=False, verbose_name='financially responsible')),
                ('has_custody', models.BooleanField(default=False, verbose_name='has custody')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarded_links', to='identity.person')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='identity.person')),
            ],
            options={
                'verbose_name': 'guardian link',
                'verbose_name_plural': 'guardian links',
                'constraints': [models.UniqueConstraint(fields=('guardian', 'student'), name='unique_guardian_student'), models.CheckConstraint(condition=models.Q(('guardian', models.F('student')), _negated=True), name='guardian_may_not_be_own_student')],
            },
        ),
    ]
