# Generated by Django 5.2.16 on 2026-07-30 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary dojo')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('ended', 'Ended')], db_index=True, default='active', max_length=16, verbose_name='status')),
                ('started_on', models.DateField(verbose_name='started on')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='ended on')),
                ('hold_reason', models.CharField(blank=True, max_length=200, verbose_name='hold reason')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='identity.dojo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='identity.person')),
            ],
            options={
                'verbose_name': 'enrolment',
                'verbose_name_plural': 'enrolments',
                'ordering': ('-started_on',),
                'indexes': [models.Index(fields=['dojo', 'status'], name='identity_en_dojo_id_5737e9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('student', 'dojo'), name='unique_live_enrollment_per_dojo'), models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True), ('is_primary', True)), fields=('student',), name='unique_primary_enrollment_per_student'), models.CheckConstraint(condition=models.Q(models.Q(('ended_on__isnull', False), ('status', 'ended')), models.Q(models.Q(('status', 'ended'), _negated=True), ('ended_on__isnull', True)), _connector='OR'), name='enrollment_ended_on_matches_status'), models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='enrollment_ended_on_gte_started_on')],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_on', models.DateField(verbose_name='effective on')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='identity.person')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('from_dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='identity.dojo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='identity.person')),
                ('to_dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='identity.dojo')),
            ],
            options={
                'verbose_name': 'transfer record',
                'verbose_name_plural': 'transfer records',
                'ordering': ('-effective_on',),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_dojo', models.F('to_dojo')), _negated=True), name='transfer_between_different_dojos')],
            },
        ),
    ]
