# Generated by Django 5.2.16 on 2026-08-05 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_enrollment_transferrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="MfaCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("totp_secret", apps.core.fields.EncryptedCharField(max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_code_hashes", models.JSONField(blank=True, default=list)),
                ("last_used_counter", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_credentials",
                        to="identity.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "multi-factor credential",
                "verbose_name_plural": "multi-factor credentials",
            },
        ),
    ]
