# Generated by Django 5.2.16 on 2026-08-05 02:35

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_mfacredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='allergies',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='allergies'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='conditions',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='medical conditions'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='do_not_spar',
            field=models.BooleanField(default=False, verbose_name='do not spar'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='doctor_contact',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='doctor contact'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_notes',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='medical notes'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medications',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='medications'),
        ),
    ]
