# Generated by Django 5.2.16 on 2026-08-05 02:41

import apps.core.fields
import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_action'),
        ('identity', '0007_student_medical_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('photo', 'Photo and video'), ('marketing', 'Marketing'), ('data_processing', 'Data processing'), ('medical', 'Medical data'), ('waiver', 'Liability waiver')], max_length=24, verbose_name='consent type')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('granted', models.BooleanField(verbose_name='granted')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recorded at')),
                ('capacity', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('guardian', 'Legal guardian')], max_length=16, verbose_name='capacity')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('signature_name', apps.core.fields.EncryptedCharField(blank=True, max_length=200, verbose_name='signature name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='core.document')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents_given', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='identity.person')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='identity.consentrecord')),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ('-granted_at', '-created_at'),
                'indexes': [models.Index(fields=['person', 'consent_type', 'version', '-granted_at'], name='identity_co_person__05f4eb_idx')],
            },
        ),
    ]
