# Generated by Django 5.2.16 on 2026-08-05 02:50

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_action'),
        ('identity', '0008_consent_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPolicy',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('photo', 'Photo and video'), ('marketing', 'Marketing'), ('data_processing', 'Data processing'), ('medical', 'Medical data'), ('waiver', 'Liability waiver')], max_length=24, verbose_name='consent type')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, help_text='Plain text shown verbatim to the signer.', verbose_name='document text')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_policies', to='core.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_policies', to='identity.organization')),
            ],
            options={
                'verbose_name': 'consent policy',
                'verbose_name_plural': 'consent policies',
                'ordering': ('consent_type', '-published_at'),
            },
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='identity.consentpolicy'),
        ),
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'consent_type', 'version'), name='unique_consent_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'consent_type'), name='unique_active_consent_policy'),
        ),
    ]
