# Generated by Django 5.2.16 on 2026-08-05 04:01

import apps.core.ids
import apps.identity.student_filters
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_consent_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSegment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('filters', models.JSONField(default=dict, validators=[apps.identity.student_filters.validate_saved_student_filters], verbose_name='filters')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_segments', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_segments', to='identity.person')),
            ],
            options={
                'verbose_name': 'student segment',
                'verbose_name_plural': 'student segments',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'owner', 'name'), name='unique_student_segment_name_per_owner')],
            },
        ),
    ]
