# Generated by Django 5.2.16 on 2026-08-05 04:34

from django.db import migrations

import apps.core.fields


def _rewrite_hold_reasons(schema_editor, transform):
    """Transform existing plaintext/ciphertext without field pre-save hooks."""
    tables = (
        (
            "identity_studentprofile",
            "identity_person",
            "person_id",
            "organization_id",
        ),
        (
            "identity_enrollment",
            "identity_dojo",
            "dojo_id",
            "organization_id",
        ),
    )
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    # Only fixed internal migration identifiers reach these backend-quoted SQL fragments.
    with connection.cursor() as cursor:
        for table, owner_table, owner_fk, organization_column in tables:
            cursor.execute(
                f"SELECT source.id, source.hold_reason, owner.{quote(organization_column)} "  # nosec B608
                f"FROM {quote(table)} source "
                f"JOIN {quote(owner_table)} owner ON source.{quote(owner_fk)} = owner.id "
                "WHERE source.hold_reason <> ''"
            )
            rows = cursor.fetchall()
            for row_id, value, organization_id in rows:
                replacement = transform(organization_id, value)
                if replacement != value:
                    cursor.execute(
                        f"UPDATE {quote(table)} SET hold_reason = %s WHERE id = %s",  # nosec B608
                        [replacement, row_id],
                    )


def encrypt_existing_hold_reasons(apps, schema_editor):
    from apps.core.encryption import encrypt, looks_encrypted

    def transform(organization_id, value):
        return value if looks_encrypted(value) else encrypt(organization_id, value)

    _rewrite_hold_reasons(schema_editor, transform)


def decrypt_existing_hold_reasons(apps, schema_editor):
    from apps.core.encryption import decrypt, looks_encrypted

    def transform(_organization_id, value):
        return decrypt(value) if looks_encrypted(value) else value

    _rewrite_hold_reasons(schema_editor, transform)


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0010_student_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="hold_reason",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=200, verbose_name="hold reason"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="hold_reason",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=200, verbose_name="hold reason"
            ),
        ),
        migrations.RunPython(
            encrypt_existing_hold_reasons,
            decrypt_existing_hold_reasons,
        ),
    ]
