# Generated by Django 5.2.16 on 2026-08-05 05:05

from django.db import migrations

import apps.core.fields


def _rewrite_notes(schema_editor, transform):
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    # Only fixed internal migration identifiers reach these backend-quoted SQL fragments.
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT link.id, link.notes, person.organization_id "  # nosec B608
            f"FROM {quote('identity_guardianlink')} link "
            f"JOIN {quote('identity_person')} person ON link.student_id = person.id "
            "WHERE link.notes <> ''"
        )
        for row_id, value, organization_id in cursor.fetchall():
            replacement = transform(organization_id, value)
            if replacement != value:
                cursor.execute(
                    f"UPDATE {quote('identity_guardianlink')} SET notes = %s WHERE id = %s",  # nosec B608
                    [replacement, row_id],
                )


def encrypt_existing_notes(apps, schema_editor):
    from apps.core.encryption import encrypt, looks_encrypted

    _rewrite_notes(
        schema_editor,
        lambda organization_id, value: (
            value if looks_encrypted(value) else encrypt(organization_id, value)
        ),
    )


def decrypt_existing_notes(apps, schema_editor):
    from apps.core.encryption import decrypt, looks_encrypted

    _rewrite_notes(
        schema_editor,
        lambda _organization_id, value: decrypt(value) if looks_encrypted(value) else value,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0011_encrypt_hold_reasons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardianlink",
            name="notes",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=255, verbose_name="notes"
            ),
        ),
        migrations.RunPython(encrypt_existing_notes, decrypt_existing_notes),
    ]
