# Generated by Django 5.2.17 on 2026-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_scope_and_encrypt_guardian_records'),
        ('ranks', '0004_style_is_ranked_alter_studentstyletrack_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='dojos', to='ranks.style', verbose_name='styles taught'),
        ),
    ]
