# Generated by Django 5.2.17 on 2026-08-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_dojo_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, editable=False, verbose_name='must change password'),
        ),
    ]
