# Generated by Django 5.2.16 on 2026-07-26 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('export', 'Exported'), ('permission_change', 'Permission changed')], max_length=32)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('actor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='identity.person')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='identity.organization')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['organization', '-at'], name='core_auditl_organiz_d7932a_idx'), models.Index(fields=['subject_type', 'subject_id', '-at'], name='core_auditl_subject_e2ba28_idx')],
            },
        ),
    ]
