# Generated by Django 5.2.16 on 2026-07-26 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0002_person_deleted_at_person_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(max_length=20, verbose_name='scope')),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='key')),
                ('value', models.JSONField(verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='identity.organization')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
                'indexes': [models.Index(fields=['organization', 'key'], name='core_settin_organiz_892a55_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'scope_type', 'scope_id', 'key'), name='unique_setting_per_scope')],
            },
        ),
    ]
