# Generated by Django 5.2.16 on 2026-07-26 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
        ('identity', '0002_person_deleted_at_person_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDataKey',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('wrapped_key', models.BinaryField()),
                ('master_key_version', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rotated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_key', to='identity.organization')),
            ],
            options={
                'verbose_name': 'organisation data key',
                'verbose_name_plural': 'organisation data keys',
            },
        ),
    ]
