# Generated by Django 5.2.16 on 2026-07-26 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationdatakey'),
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('waiver', 'Signed waiver'), ('medical', 'Medical letter'), ('identity', 'Identity document'), ('certificate', 'Certificate'), ('photo', 'Photograph'), ('other', 'Other')], max_length=16, verbose_name='kind')),
                ('original_filename', models.CharField(max_length=255, verbose_name='file name')),
                ('storage_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('content_type', models.CharField(editable=False, max_length=100)),
                ('byte_size', models.PositiveIntegerField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.organization')),
                ('subject_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.person')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='identity.person')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'kind'], name='core_docume_organiz_8f245b_idx'), models.Index(fields=['subject_person', '-created_at'], name='core_docume_subject_e670dc_idx')],
            },
        ),
    ]
