# Generated by Django 5.2.16 on 2026-07-26 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document'),
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('student', 'Student'), ('session', 'Session'), ('enrollment', 'Enrollment'), ('invoice', 'Invoice')], db_index=True, max_length=16, verbose_name='subject type')),
                ('subject_id', models.UUIDField(db_index=True, verbose_name='subject id')),
                ('body', models.TextField(verbose_name='body')),
                ('visibility', models.CharField(choices=[('private', 'Private — author only'), ('instructors', 'Instructors at this dojo'), ('admins', 'Dojo and org administrators'), ('parent_visible', "Student's guardians can read it")], default='instructors', max_length=16, verbose_name='visibility')),
                ('pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to='identity.person')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='identity.organization')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ('-pinned', '-created_at'),
                'indexes': [models.Index(fields=['subject_type', 'subject_id', '-pinned', '-created_at'], name='note_subject_pinned_idx')],
            },
        ),
    ]
