# Generated by Django 5.2.16 on 2026-07-26 12:34

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_note'),
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3, verbose_name='from')),
                ('quote_currency', models.CharField(max_length=3, verbose_name='to')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='rate')),
                ('effective_from', models.DateField(default=datetime.date.today, verbose_name='effective from')),
                ('source', models.CharField(choices=[('manual', 'Set by the organisation'), ('feed', 'Imported from a rate feed'), ('settlement', 'From a payment settlement')], default='manual', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='identity.organization')),
            ],
            options={
                'verbose_name': 'exchange rate',
                'verbose_name_plural': 'exchange rates',
                'ordering': ('-effective_from',),
                'indexes': [models.Index(fields=['organization', 'base_currency', 'quote_currency', '-effective_from'], name='core_exchan_organiz_0aac79_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'base_currency', 'quote_currency', 'effective_from'), name='unique_rate_per_pair_and_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='rate_is_positive')],
            },
        ),
    ]
