# Generated by Django 5.2.16 on 2026-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('export', 'Exported'), ('permission_change', 'Permission changed')], max_length=32),
        ),
    ]
