# Generated by Django 5.2.17 on 2026-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_encrypt_note_bodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('waiver', 'Signed waiver'), ('medical', 'Medical letter'), ('identity', 'Identity document'), ('certificate', 'Certificate'), ('photo', 'Photograph'), ('profile_photo', 'Profile picture'), ('other', 'Other')], max_length=16, verbose_name='kind'),
        ),
    ]
