# Generated by Django 5.2.17 on 2026-08-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('waiver', 'Signed waiver'), ('medical', 'Medical letter'), ('identity', 'Identity document'), ('certificate', 'Certificate'), ('photo', 'Photograph'), ('profile_photo', 'Profile picture'), ('event_image', 'Event image'), ('event_attachment', 'Event attachment'), ('other', 'Other')], max_length=16, verbose_name='kind'),
        ),
    ]
