"""Attendance records — TODO 1.5.1/1.5.3, plan §4.5.

This is the table the whole product is judged on. It is written from a phone at
the edge of a hall with bad wifi, by an instructor who has thirty seconds before
warm-ups, and it is later read as evidence for grading eligibility, for billing
disputes and for "was my child at training on Tuesday".

Two consequences shape the schema:

* ``client_generated_id`` exists from day one. The offline PWA (TODO 1.6) marks a
  class with no network and syncs later, possibly twice. Dedupe cannot be
  invented afterwards — the id has to come from the client that created the mark.
* Records are never deleted. A correction is an update with an audit trail
  (TODO 1.5.5), because "the record disappeared" is indistinguishable from
  "the record was never made" when a safeguarding question is asked a year on.
"""

from __future__ import annotations

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.core.managers import ScopedManager
from apps.core.models import TenantScopedModel


class AttendanceRecord(TenantScopedModel):
    """One student's attendance at one class session."""

    tenant_org_path = "session__dojo__organization_id"
    tenant_dojo_path = "session__dojo_id"
    #: The session's dojo owns the record; the student and whoever marked them
    #: must belong to the same organisation.
    same_organization_fields = ("session", "student", "marked_by")

    class Status(models.TextChoices):
        PRESENT = "present", _("Present")
        LATE = "late", _("Late")
        ABSENT = "absent", _("Absent")
        EXCUSED = "excused", _("Excused")
        #: Training at a dojo they are not enrolled at — plan §4.3. Counts as
        #: attendance; kept distinct so the host dojo's numbers stay honest.
        VISITING = "visiting", _("Visiting")

    class Method(models.TextChoices):
        ROSTER = "roster", _("Instructor roster")
        KIOSK_QR = "kiosk_qr", _("Kiosk — QR card")
        KIOSK_PIN = "kiosk_pin", _("Kiosk — PIN")
        SELF = "self", _("Self check-in")
        IMPORT = "import", _("Imported")

    #: Statuses that mean the student was actually in the room. Reports and
    #: grading eligibility must agree on this, so it lives here and not in each
    #: query.
    ATTENDED_STATUSES = ("present", "late", "visiting")

    session = models.ForeignKey(
        "scheduling.ClassSession",
        on_delete=models.PROTECT,
        related_name="attendance_records",
    )
    student = models.ForeignKey(
        "identity.Person",
        on_delete=models.PROTECT,
        related_name="attendance_records",
    )
    status = models.CharField(
        _("status"),
        max_length=16,
        choices=Status.choices,
        default=Status.PRESENT,
        db_index=True,
    )
    method = models.CharField(
        _("method"),
        max_length=16,
        choices=Method.choices,
        default=Method.ROSTER,
    )
    marked_by = models.ForeignKey(
        "identity.Person",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="attendance_marked",
    )
    marked_at = models.DateTimeField(_("marked at"), default=timezone.now)

    #: Generated by the client that created the mark, so a replayed offline queue
    #: is recognised as the same act rather than applied twice. Blank for marks
    #: made online, where the request itself is the only attempt.
    client_generated_id = models.CharField(max_length=64, blank=True, editable=False)
    note = models.CharField(_("note"), max_length=255, blank=True)

    objects = ScopedManager()

    class Meta:
        verbose_name = _("attendance record")
        verbose_name_plural = _("attendance records")
        ordering = ("-marked_at",)
        constraints = [
            models.UniqueConstraint(
                fields=["session", "student"],
                name="unique_attendance_per_session_student",
            ),
            # The idempotency key. Partial, because online marks leave it blank
            # and several blanks per session are normal.
            models.UniqueConstraint(
                fields=["client_generated_id"],
                condition=~models.Q(client_generated_id=""),
                name="unique_attendance_client_generated_id",
            ),
        ]
        indexes = [
            models.Index(fields=["session", "status"]),
            models.Index(fields=["student", "-marked_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.student} — {self.get_status_display()} @ {self.session}"

    @staticmethod
    def _organization_of(obj):
        """Reach the organisation through a session's dojo."""
        if obj is not None and obj.__class__.__name__ == "ClassSession":
            return obj.dojo.organization_id
        return TenantScopedModel._organization_of(obj)

    @property
    def attended(self) -> bool:
        return self.status in self.ATTENDED_STATUSES
