# Generated by Django 5.2.16 on 2026-07-26 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('rrule', models.CharField(help_text='RFC 5545 recurrence rule, e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR', max_length=255, verbose_name='recurrence rule')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duration (minutes)')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='room')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum age')),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum age')),
                ('active_from', models.DateField(verbose_name='active from')),
                ('active_to', models.DateField(blank=True, null=True, verbose_name='active until')),
                ('counts_toward', models.JSONField(blank=True, default=list, help_text='Tags such as ["kata", "kihon"] used for grading eligibility.', verbose_name='counts toward')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_templates', to='identity.dojo')),
                ('rank_max', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_templates_max', to='ranks.rank')),
                ('rank_min', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_templates_min', to='ranks.rank')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_templates', to='ranks.style')),
            ],
            options={
                'verbose_name': 'class template',
                'verbose_name_plural': 'class templates',
                'ordering': ('dojo', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='scheduled', max_length=16, verbose_name='status')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='room')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='identity.dojo')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.classtemplate')),
            ],
            options={
                'verbose_name': 'class session',
                'verbose_name_plural': 'class sessions',
                'ordering': ('-starts_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='session_ends_at_gt_starts_at')],
            },
        ),
        migrations.CreateModel(
            name='ClosurePeriod',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField(verbose_name='starts on')),
                ('ends_on', models.DateField(verbose_name='ends on')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('suppress_billing', models.BooleanField(default=False, help_text='When set, billing is paused for this closure period.', verbose_name='suppress billing')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closure_periods', to='identity.dojo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_periods', to='identity.organization')),
            ],
            options={
                'verbose_name': 'closure period',
                'verbose_name_plural': 'closure periods',
                'ordering': ('organization', 'starts_on'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='closure_ends_on_gte_starts_on')],
            },
        ),
    ]
