# Generated by Django 5.2.16 on 2026-07-26 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('source', models.CharField(choices=[('manual', 'manual'), ('imported', 'imported'), ('builtin', 'builtin')], default='manual', max_length=16, verbose_name='source')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='external id')),
                ('is_recurring_annually', models.BooleanField(default=False, help_text='Fixed-date holidays such as 1 January. Lunar holidays are False.', verbose_name='recurring annually')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='identity.organization')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ('organization', 'date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HolidayObservance',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observance', models.CharField(choices=[('closed', 'closed'), ('open', 'open'), ('reduced_schedule', 'reduced schedule')], default='open', max_length=16, verbose_name='observance')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_observance', to='scheduling.closureperiod')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_observances', to='identity.dojo')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observances', to='scheduling.holiday')),
            ],
            options={
                'verbose_name': 'holiday observance',
                'verbose_name_plural': 'holiday observances',
            },
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('organization', 'date', 'name'), name='unique_holiday_per_org_date_name'),
        ),
        migrations.AddConstraint(
            model_name='holidayobservance',
            constraint=models.UniqueConstraint(fields=('holiday', 'dojo'), name='unique_holiday_observance_per_dojo'),
        ),
    ]
