# Generated by Django 5.2.17 on 2026-08-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_holiday_holidayobservance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='moved_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='moved from'),
        ),
    ]
