# Generated by Django 5.2.17 on 2026-08-15 13:26

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_scope_and_encrypt_guardian_records'),
        ('scheduling', '0003_classsession_moved_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInstructor',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_substitute', models.BooleanField(default=False, verbose_name='substitute')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_sessions', to='identity.person')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_by', to='identity.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_instructors', to='scheduling.classsession')),
            ],
            options={
                'verbose_name': 'session instructor',
                'verbose_name_plural': 'session instructors',
                'ordering': ('session', 'person'),
                'constraints': [models.UniqueConstraint(fields=('session', 'person'), name='unique_instructor_per_session')],
            },
        ),
        migrations.CreateModel(
            name='TemplateInstructor',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_class_templates', to='identity.person')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_instructors', to='scheduling.classtemplate')),
            ],
            options={
                'verbose_name': 'template instructor',
                'verbose_name_plural': 'template instructors',
                'ordering': ('template', 'person'),
                'constraints': [models.UniqueConstraint(fields=('template', 'person'), name='unique_instructor_per_template')],
            },
        ),
    ]
