#!/usr/bin/env bash
# =============================================================================
# Generate a .env for a self-hosted BokyDojo.
#
#   ./scripts/init-env.sh
#
# ⚠ Generates real secrets rather than shipping placeholders. The application
# refuses to boot on a known-placeholder DJANGO_SECRET_KEY or a missing
# encryption key (config/settings/guards.py), which is deliberate: a self-host
# deployment running on the example values is the failure mode that guard
# exists to prevent.
# =============================================================================
set -euo pipefail

TARGET="${1:-.env}"

if [ -e "$TARGET" ]; then
    echo "$TARGET already exists — refusing to overwrite it." >&2
    echo "Delete it first if you really mean to regenerate the secrets." >&2
    echo >&2
    echo "⚠ Regenerating DJANGO_FIELD_ENCRYPTION_KEYS makes every encrypted" >&2
    echo "  medical and safeguarding record unreadable. Keep a backup." >&2
    exit 1
fi

# Prefer python3; fall back to openssl so this works on a bare server.
if command -v python3 >/dev/null 2>&1; then
    secret_key="$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')"
    setup_token="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    field_key="1:$(python3 -c 'import base64,os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())')"
    db_password="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
elif command -v openssl >/dev/null 2>&1; then
    secret_key="$(openssl rand -base64 64 | tr -d '\n=' | tr '+/' '-_')"
    setup_token="$(openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_')"
    field_key="1:$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')"
    db_password="$(openssl rand -base64 24 | tr -d '\n=' | tr '+/' '-_')"
else
    echo "Need python3 or openssl to generate secrets." >&2
    exit 1
fi

cat > "$TARGET" <<EOF
# Generated by scripts/init-env.sh — keep this file out of version control.
# ⚠ DJANGO_FIELD_ENCRYPTION_KEYS decrypts medical and safeguarding data.
#    Losing it loses those records. Back it up somewhere other than this server.

DJANGO_SECRET_KEY=${secret_key}
DJANGO_DEBUG=false
DJANGO_FIRST_RUN_TOKEN=${setup_token}
DJANGO_FIELD_ENCRYPTION_KEYS=${field_key}

# ⚠ Every hostname this instance answers on. Django refuses requests for
# anything not listed, and the guard refuses to boot when this is empty.
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

DJANGO_DEFAULT_FROM_EMAIL=BokyDojo <noreply@localhost>

POSTGRES_DB=bokydojo
POSTGRES_USER=bokydojo
POSTGRES_PASSWORD=${db_password}
POSTGRES_HOST=db
POSTGRES_PORT=5432

REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# ⚠ Required, and deliberately so (plan §12.9): password reset and every
# notification go through it, and a deployment that silently cannot send mail
# is worse than one that refuses to start. The placeholder below lets the stack
# boot for evaluation — password reset will fail until it is real. Use a
# transactional provider; a residential IP lands in spam.
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=true

# Ports published on the host. Defaults are high so this works under rootless
# Podman; a public deployment wants 80 and 443.
BOKYDOJO_HTTP_PORT=8080
BOKYDOJO_HTTPS_PORT=8443

# The domain Caddy serves and requests a certificate for. Leave as localhost for
# a local trial (Caddy issues an internal self-signed certificate).
DOMAIN=localhost
EOF

chmod 600 "$TARGET"

echo "Wrote $TARGET (mode 600)."
echo
echo "First-run setup token: ${setup_token}"
echo "  Needed once at /setup/ to create the organisation and owner account."
echo
echo "⚠ Back up DJANGO_FIELD_ENCRYPTION_KEYS. Without it, encrypted medical and"
echo "  safeguarding records cannot be read back."
