# Generated by Django 5.2.16 on 2026-07-30 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_enrollment_transferrecord'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused'), ('visiting', 'Visiting')], db_index=True, default='present', max_length=16, verbose_name='status')),
                ('method', models.CharField(choices=[('roster', 'Instructor roster'), ('kiosk_qr', 'Kiosk — QR card'), ('kiosk_pin', 'Kiosk — PIN'), ('self', 'Self check-in'), ('import', 'Imported')], default='roster', max_length=16, verbose_name='method')),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='marked at')),
                ('client_generated_id', models.CharField(blank=True, editable=False, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='identity.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='scheduling.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='identity.person')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ('-marked_at',),
                'indexes': [models.Index(fields=['session', 'status'], name='attendance__session_8dae34_idx'), models.Index(fields=['student', '-marked_at'], name='attendance__student_392ec6_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_per_session_student'), models.UniqueConstraint(condition=models.Q(('client_generated_id', ''), _negated=True), fields=('client_generated_id',), name='unique_attendance_client_generated_id')],
            },
        ),
    ]
