# Generated by Django 5.2.17 on 2026-08-17 03:27

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0012_scope_and_encrypt_guardian_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('students', 'students and guardians'), ('attendance', 'historical attendance'), ('ranks', 'rank history')], max_length=16, verbose_name='kind')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('is_dry_run', models.BooleanField(default=True, verbose_name='dry run')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('failed', 'failed')], default='completed', max_length=16, verbose_name='status')),
                ('mapping', models.JSONField(blank=True, default=dict, verbose_name='column mapping')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='rows')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='created')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='updated')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='errors')),
                ('outcomes', models.JSONField(blank=True, default=list, verbose_name='row outcomes')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='failure reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='identity.dojo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='identity.organization')),
            ],
            options={
                'verbose_name': 'import run',
                'verbose_name_plural': 'import runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportedRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=32, verbose_name='entity type')),
                ('source_key', models.CharField(max_length=255, verbose_name='source key')),
                ('object_id', models.UUIDField(verbose_name='object id')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_records', to='identity.organization')),
            ],
            options={
                'verbose_name': 'imported record',
                'verbose_name_plural': 'imported records',
                'indexes': [models.Index(fields=['organization', 'entity_type', 'object_id'], name='imports_imp_organiz_a6ac5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'entity_type', 'source_key'), name='unique_import_key_per_org_entity')],
            },
        ),
    ]
