# Generated by Django 5.2.16 on 2026-07-26 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_person_deleted_at_person_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='identity.organization')),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RankLadder',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('applies_to', models.CharField(choices=[('adult', 'Adult'), ('junior', 'Junior')], max_length=8, verbose_name='applies to')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladders', to='ranks.style')),
            ],
            options={
                'verbose_name': 'rank ladder',
                'verbose_name_plural': 'rank ladders',
                'ordering': ('style', 'applies_to', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(help_text='Defines progression within a ladder. Unique per ladder.', verbose_name='order')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('belt_colour', models.CharField(blank=True, max_length=30, verbose_name='belt colour')),
                ('stripe_count', models.PositiveSmallIntegerField(default=0, verbose_name='stripe count')),
                ('min_months_at_previous', models.PositiveIntegerField(default=0, verbose_name='min months at previous rank')),
                ('min_classes_since_previous', models.PositiveIntegerField(default=0, verbose_name='min classes since previous rank')),
                ('min_age', models.PositiveSmallIntegerField(default=0, verbose_name='min age')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='ranks.rankladder')),
            ],
            options={
                'verbose_name': 'rank',
                'verbose_name_plural': 'ranks',
                'ordering': ('ladder', 'order'),
                'constraints': [models.UniqueConstraint(fields=('ladder', 'order'), name='unique_rank_order_per_ladder')],
            },
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_style_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='rankladder',
            constraint=models.UniqueConstraint(fields=('style', 'name'), name='unique_ladder_name_per_style'),
        ),
        migrations.AddConstraint(
            model_name='rankladder',
            constraint=models.UniqueConstraint(fields=('style', 'applies_to'), name='unique_ladder_applies_to_per_style'),
        ),
    ]
