# Generated by Django 5.2.16 on 2026-07-26 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStyleTrack',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField(verbose_name='started on')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='ended on')),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Moved to another ladder'), ('ended', 'Ended')], default='active', max_length=16, verbose_name='status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('current_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ranks.rank')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='ranks.rankladder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_tracks', to='identity.person')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='ranks.style')),
            ],
            options={
                'verbose_name': 'student style track',
                'verbose_name_plural': 'student style tracks',
                'ordering': ('student', 'style'),
                'indexes': [models.Index(fields=['student', 'status'], name='ranks_stude_student_7bade3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'style'), name='unique_active_track_per_student_style'), models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='track_ended_on_after_started_on'), models.CheckConstraint(condition=models.Q(models.Q(('ended_on__isnull', True), ('status', 'active')), models.Q(('status', 'active'), _negated=True), _connector='OR'), name='active_track_has_no_end_date')],
            },
        ),
    ]
