# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emergencycontact_studentprofile_guardianlink'),
        ('ranks', '0002_studentstyletrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankAward',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_on', models.DateField(verbose_name='awarded on')),
                ('recognition', models.CharField(choices=[('internal', 'Awarded here'), ('recognised', 'Recognised from another organisation'), ('provisional', 'Provisionally recognised'), ('honorary', 'Honorary')], default='internal', max_length=16, verbose_name='recognition')),
                ('awarded_by_external_org', models.CharField(blank=True, max_length=200, verbose_name='awarding organisation')),
                ('certificate_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=500)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks_awarded', to='identity.person')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='ranks.rank')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks_revoked', to='identity.person')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='ranks.studentstyletrack')),
            ],
            options={
                'verbose_name': 'rank award',
                'verbose_name_plural': 'rank awards',
                'ordering': ('-awarded_on',),
                'indexes': [models.Index(fields=['track', '-awarded_on'], name='ranks_ranka_track_i_f2ff59_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('track', 'rank'), name='unique_live_award_per_track_rank')],
            },
        ),
    ]
