# Generated by Django 5.2.17 on 2026-08-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0003_rankaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_ranked',
            field=models.BooleanField(default=True, help_text='Turn off for arts with no grading, such as boxing or fitness classes.', verbose_name='uses ranks'),
        ),
        migrations.AlterField(
            model_name='studentstyletrack',
            name='ladder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='ranks.rankladder'),
        ),
    ]
