# Generated by Django 5.2.17 on 2026-08-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_dojo_styles'),
        ('ranks', '0004_style_is_ranked_alter_studentstyletrack_ladder'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rankladder',
            name='unique_ladder_applies_to_per_style',
        ),
        migrations.AddField(
            model_name='rankladder',
            name='dojo',
            field=models.ForeignKey(blank=True, help_text="Leave empty for the organisation's default belts for this style.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_ladders', to='identity.dojo', verbose_name='dojo'),
        ),
        migrations.AddConstraint(
            model_name='rankladder',
            constraint=models.UniqueConstraint(condition=models.Q(('dojo__isnull', True)), fields=('style', 'applies_to'), name='unique_org_ladder_applies_to_per_style'),
        ),
        migrations.AddConstraint(
            model_name='rankladder',
            constraint=models.UniqueConstraint(condition=models.Q(('dojo__isnull', False)), fields=('style', 'dojo', 'applies_to'), name='unique_dojo_ladder_applies_to_per_style'),
        ),
    ]
