# Generated by Django 5.2.17 on 2026-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0005_remove_rankladder_unique_ladder_applies_to_per_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankladder',
            name='applies_to',
            field=models.CharField(choices=[('all', 'Everyone'), ('adult', 'Adult'), ('junior', 'Junior')], max_length=8, verbose_name='applies to'),
        ),
    ]
